### ISSUE TITLE
Pipeline fails if 0 pathways found in one of the conditions

### ISSUE THREAD

**Issue by LaurenceKuhl** [qbic-pipelines/rnadeseq#86] opened 2021-03-05 09:17 UTC
Hi there,

I am currently running the pipeline with treatment (control, 25% and 50% of the drug) as condition. There is no pathways found between 25% and 50% of the drug intake : 

```
  [1] "DE_contrast_condition_treatment_50.CSF_vs_25.CSF"
  [1] "Number of genes in query:"
  [1] 997
  [1] "Number of pathways found:"
  integer(0)

```
which causes the pipeline to fail at `pathway_analysis.R`: 

```
##############################################################################
  Pathview is an open source software package distributed under GNU General
  Public License version 3 (GPLv3). Details of GPLv3 is available at
  http://www.gnu.org/licenses/gpl-3.0.html. Particullary, users are required to
  formally cite the original Pathview paper (not just mention it) in publications
  or products. For details, do citation("pathview") within R.
  
  The pathview downloads and uses KEGG data. Non-academic uses may require a KEGG
  license agreement (details at http://www.kegg.jp/kegg/legal.html).
  ##############################################################################
  
  No results to show
```

I think it's the condition here that needs to be checked https://github.com/qbic-pipelines/rnadeseq/blob/abe742731af96ae25787f3a928a82cd4951d1a1d/bin/pathway_analysis.R#L204

I opened an issue just as a reminder, maybe it'll be a small task i can do at the hackathon :)
Best,
Laurence

**Comment by ggabernet** [comment] 2021-03-08 13:14
Hi Laurence, 

thanks for reporting this issue. What version of the pipeline are you using? What is exactly the Nextflow error message that you got? Here I can see output messages but not an error. Maybe it is in the work directory under `.command.err` or `.command.log`?

**Comment by ggabernet** [comment] 2021-04-14 08:03
Hi @LaurenceKuhl ,
if you have it could you post the full error message here? From the code it looks like it is already checking if there are any pathway results and just printing "No results to show" if there are none. So I would need to double check what was exactly the error

**Comment by LaurenceKuhl** [comment] 2022-02-18 11:23
oh wow i just noticed now i totally ignored your questions Gisela i'm sorry somehow i never saw these questions! 
Oskar and I had a chat and he's going to manually reproduce the error, otherwise I'll pull the data back up where this happened.
Best,
Laurence

**Comment by ggabernet** [comment] 2022-02-18 11:29
awesome, thanks for the help

**Comment by WackerO** [comment] 2022-02-24 14:57
Closing this issue for now as I cannot reproduce it for the life of me. Please do reopen if it appears again!

**Closed by WackerO** 2022-02-24 14:57 UTC
