### ISSUE TITLE
Pathway analysis folder should not be created if pathway analysis was set to FALSE

### ISSUE THREAD

**Issue by qbicStefanC** [qbic-pipelines/rnadeseq#120] opened 2022-04-28 09:15 UTC
I usually define pathway analysis in a yml file like given in the `testdata` here: https://github.com/qbic-pipelines/rnadeseq/blob/master/testdata/report_options.yml

If I change there the option to

```
KEGG: FALSE
```
and run it as usual with : 
`--report_options 'report_options.yml'`

I still get the `pathway_analysis` folder created. This should be changed.
Thanks

**Comment by ggabernet** [comment] 2022-07-25 11:15
@WackerO will just check if the issue is still there in the new implementation, and if not just close it :)

**Comment by WackerO** [comment] 2022-08-05 11:39
This is implemented now :)

**Closed by WackerO** 2022-08-05 11:39 UTC
